### ISSUE TITLE
Publishing provider to tapir

### ISSUE THREAD

**Issue by kolayne2021** [PacoVK/tapir#287]
Hi I am trying to publish an existing provider to tapir, so I added my gpg keys to tapir envs, then created a  zip-archive of the provider:
```
gpg --generate-key
shasum -a 256 dev-modules_3.0.2_linux_amd64.zip >  dev-modules_3.0.2_linux_amd64_SHA256SUMS
gpg --detach-sign dev-modules_3.0.2_linux_amd64_SHA256SUMS

Archive:  archive.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 2023-09-25 16:10 00000000  archive/
     100  Defl:N       91   9% 2023-09-25 16:10 a822df4d  archive/dev-modules_3.0.2_linux_amd64_SHA256SUMS
     438  Stored      438   0% 2023-09-25 16:10 50cb76e2  archive/dev-modules_3.0.2_linux_amd64_SHA256SUMS.sig
 7019352  Stored  7019352   0% 2023-09-25 16:10 e1f917b2  archive/dev-modules_3.0.2_linux_amd64.zip
--------          -------  ---                            -------
 7019890          7019881   0%                            4 files

```

But when i try to post provider to tapir I get an error: 
`curl -X POST --fail-with-body -F archive=@archive.zip https://tapir.dev.local/terraform/providers/v1/dev/modules/3.0.2
curl: (22) The requested URL returned error: 500
{"errorId":"b5985a8b-d172-4429-a706-9682a7208edc","errors":[{"message":"An unexpected error has occurred. Please raise an issue if you think this is a bug."}]}
The application works behind nginx with valid certificates.
`
What am I doing wrong? 
Thanks!

**Comment by PacoVK** [comment]
Thanks for reporting. I think your provider does not match all of the criteria's mentioned in the [official Terraform](https://developer.hashicorp.com/terraform/registry/providers/publishing#manually-preparing-a-release) docs for publishing providers.
Since Tapir gets all relevant Infos about the provider via the API call, your artifact can be named line you did (archive.zip) but it's still required to have the binaries with proper names instead of zip files in the archive ☺️ makes sense?

**Comment by kolayne2021** [comment]
You were absolutely right. Thank you! 
I've sent data to tapir:
`curl -X POST --fail-with-body -F archive=@archive.zip https://tapir.dev.local/terraform/providers/v1/terraform-provider-openstack/openstack/1.51.1
`
I tried with official openstack provider. 
But now I have another one issue ( I'm sorry for it ). My terraform manifest:
`cat main.tf
terraform {
  required_providers {
    openstack = {
      source = "tapir.dev.local/terraform-provider-openstack/openstack"
      version = "1.51.1"
    }
  }
}

provider "openstack" {
  cloud = "openstack"
}
`
And my error:
`terraform init

Initializing the backend...

Initializing provider plugins...
- Finding tapir.dev.local/terraform-provider-openstack/openstack versions matching "1.51.1"...
╷
│ Error: Failed to install provider
│
│ Error while installing tapir.dev.local/terraform-provider-openstack/openstack v1.51.1: could not query provider registry for
│ tapir.dev.local/terraform-provider-openstack/openstack: failed to retrieve authentication checksums for provider: 404 Not Found returned from tapir.dev.local:443
╵
`
My tapir env's:
`environment:
      - BACKEND_CONFIG=elasticsearch
      - BACKEND_ELASTICSEARCH_HOST=opensearch-node1:9200
      - STORAGE_CONFIG=local
      - REGISTRY_HOSTNAME=tapir.dev.local
      - REGISTRY_PORT=443
      - API_MAX_BODY_SIZE=100M
      - REGISTRY_KEYS....`

**Comment by kolayne2021** [comment]
You were absolutely right! Thank you!

**Comment by PacoVK** [comment]
You are welcome :) closing this as there is no issue
