### ISSUE TITLE
Update Docs / gif to also demonstrate user management

### ISSUE THREAD

**Issue by tlchaffi** [PacoVK/tapir#371]
On this file https://github.com/PacoVK/tapir/blob/main/docs/images/tapir.gif
Could we update the workflow to demonstrate how users are managed?

**Comment by WeiMengXS** [comment]
From my experience, if you have deployed Keycloak, you can log in to its administration console for management purposes.
It is recommended to learn about it here [Keycloak](https://www.keycloak.org/)
<img width="1440" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/39400413-683b-4408-bf56-fa9a097b478f">

**Comment by PacoVK** [comment]
Tapir does not know users, it integrates with IDPs like Keycloak via OIDC. You can use any OIDC provider you like. If the OIDC provider does not provide an `end-session-path` you currently cannot logout via the UI. IDPs like Keycloak provide such endpoint. Hence, they are fully supported :) 
Mind that the token the IDP issues needs to pass a role called `admin` for users that should be able to administer Deploykeys.

**Comment by tlchaffi** [comment]
Ahhh okay. So, like a traditional SCIM mapping would occur in other systems, in this case we're doing straight user and user role mapping (for the admin) explicitly from the IdP via OIDC.

**Comment by tlchaffi** [comment]
Ahhh okay. So, like a traditional SCIM mapping would occur in other systems, in this case we're doing straight user and user role mapping (for the admin) explicitly from the IdP via OIDC.
