### ISSUE TITLE
When I access tapir through the domain name, I cannot create the deployKey.

### ISSUE THREAD

**Issue by WeiMengXS** [PacoVK/tapir#373]
When I access tapir through the domain name, I cannot create the deployKey, but I can create it directly through ip+port.
An error occurred as a cross-domain request was rejected.

<img width="1727" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/70140067-3739-4bc9-8de9-60e7a9219f8a">

<img width="865" alt="image" src="https://github.com/PacoVK/tapir/assets/54929266/450a7d3f-fbe8-41c6-9300-ff2906466dc9">

**Comment by akuzminsky** [comment]
The same error happens when Tapir runs on a container in AWS ECS behind load balancer.
An HTTP sessions looks like this:

```
POST /management/deploykey/infrahouse-cloud-init-aws HTTP/1.1
X-Forwarded-For: 23.123.142.164
X-Forwarded-Proto: https
X-Forwarded-Port: 443
Host: registry.infrahouse.com
X-Amzn-Trace-Id: Root=1-65e4db15-5b1e54bb5c7bc9b33898a19a
Content-Length: 0
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
accept: */*
accept-language: en-US,en;q=0.5
accept-encoding: gzip, deflate, br
referer: https://registry.infrahouse.com/management
origin: https://registry.infrahouse.com
dnt: 1
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
```

```
HTTP/1.1 403 CORS Rejected - Invalid origin
content-length: 0
```
