### ISSUE TITLE
Can we reuse deploy key

### ISSUE THREAD

**Issue by loispostula** [PacoVK/tapir#395]
We are starting to use tapir, it looks very promising.

We have about a 100 modules that are currently deployed via ci/cd using git tags. We'd like to transition them to use tapir. 

But it seems cumbersome to create, store, and manage that amount of deploy keys.

Is it possible to either:
* Reuse a deploy key for multiple modules
* Create and manage them using a terraform provider?

**Comment by PacoVK** [comment]
thanks for your request @loispostula 
Indeed this is not ideally handled. As of now you can not share neither manage them via terraform provider (may be viable option) 
However, i see a use case and consider to come up with an optimization that allows to create deploykeys, that could be scoped to namespaces. In that case i still would distinguish between deploykeys for modules and providers. 
WDYT?

**Comment by loispostula** [comment]
I think that would makes a lot of sense. fyi currently, we source the deploykey from the elasticsearch directly which is easier to handle from a ci/cd pov, as we only need to manage the access to the backend (not ideal)

**Comment by PacoVK** [comment]
@all-contributors please add @loispostula  for code, docs, ideas
