### ISSUE TITLE
Management and Providers tabs throw 404 Error on 0.7.1

### ISSUE THREAD

**Issue by TomBeckett** [PacoVK/tapir#401]
On the latest `0.7.1` release we receive the following error:

```json
{"errorId":"037e63fc-536a-422d-81ed-2d0033f69e1f","errors":[{"message":"An unexpected error has occurred. Please raise an issue if you think this is a bug."}]}
```

When viewing `/management` or `providers` tabs.

**Comment by PacoVK** [comment]
The PR is an intermediate solution. Actually requests seem no longer to go through Quinoa handler first, causing the issue at hand. So i need to investigate further to see whats happening. Right now, Tapir can be used but UI related URLS are not directly callable anymore...

**Comment by PacoVK** [comment]
The issue is https://github.com/quarkiverse/quarkus-quinoa/issues/666 the solution is rather simple. I will provide a fix soon

**Comment by PacoVK** [comment]
@all-contributors add @TomBeckett  for example, code
