### ISSUE TITLE
OpenTofu Support

### ISSUE THREAD

**Issue by Kruemelmann** [PacoVK/tapir#423]
Hi :)

I have a little question. Are there plans to support both Terraform and OpenTofu in the future? Currently OpenTofu is a drop in replacement but this may change in the future.

**Comment by PacoVK** [comment]
Hey @Kruemelmann sorry for the late response. There are no concrete plans yet, because there is no difference and in terms of registry compatibility I do not expect any as of now. However, this is something to keep in mind and reevaluate for a solution once there is a difference 😊
