### ISSUE TITLE
Deploykeys not showing

### ISSUE THREAD

**Issue by cedricbraekevelt** [PacoVK/tapir#424]
Hi @PacoVK , 

I'm using CosmosDB with verison 0.8.0. When i create a deploykey it works correctly. But it's not showing in the GUI.
![image](https://github.com/PacoVK/tapir/assets/26713978/d035a2c4-1a60-4ec4-9ef2-57ab2d5e42a4)
However they are being created in CosmosDB
![image](https://github.com/PacoVK/tapir/assets/26713978/70b95840-ec34-4e0e-8e02-db6cd7cf9cb3)
 
(This was also in 0.7.0 the case for me)

**Comment by PacoVK** [comment]
Hey @cedricbraekevelt thanks for this issue. I am trying to investigate as soon as possible and track the progress here.

**Comment by trumsey2005** [comment]
I'm seeing this behavior as well but on 0.8.0 using azure container app... there is a cors error present in the dev tools
![image](https://github.com/PacoVK/tapir/assets/92137246/3a99c985-9b5d-49da-8196-2a5f665b21ff)

**Comment by PacoVK** [comment]
@trumsey2005  thanks for pointinng that out, unfortunately i had no time yet to dig into that, but it is on top of my list

**Comment by cedricbraekevelt** [comment]
Hi @PacoVK,

I'm looking forward to this being solved, I've tried the platform using the keys from  the cosmosdb. 
And I like it, I'll post a blog on how to set it up once this issue is resolved!

**Comment by PacoVK** [comment]
Hey @cedricbraekevelt i will release end of this week a fix :)
