### ISSUE TITLE
Validation of module version

### ISSUE THREAD

**Issue by loispostula** [PacoVK/tapir#433]
The terraform registry protocol state that [module version](https://developer.hashicorp.com/terraform/internals/module-registry-protocol#module-versions) should follow strict semver specification. 

A validation should be added to the module endpoint

**Comment by PacoVK** [comment]
Thanks for this input, while i see your point, i think users of Tapir should be free to choose on a versioning strategy. Although it is recommended to go with SemVer i dont see a drawback in not enforcing it :)

**Comment by PacoVK** [comment]
After this popped up in #455  again, i saw that i was mistaken. Hence this will be added soon. Thanks again for reporting this

**Comment by PacoVK** [comment]
Released in version 0.9.1
