### ISSUE TITLE
bug: Scope validation is not working

### ISSUE THREAD

**Issue by loispostula** [PacoVK/tapir#449]
In #445 we introduced scopable key and a validation on the scope parameter.

It seems that quarkus is doing [case sensitive validation](https://github.com/PacoVK/tapir/blob/main/src/main/java/core/tapir/DeployKeyScope.java#L4-L7), so either we need to make it insensitive, or pass capitalize value of those from the [frontend](https://github.com/PacoVK/tapir/blob/main/src/main/webui/src/components/forms/DeployKeyForm.tsx#L18-L19)

@PacoVK Please do not release 0.9, it' s not working

**Comment by PacoVK** [comment]
Thanks for the quick, fix!
