### ISSUE TITLE
Missing Version Validation on Module Upload Allows Unsupported Formats

### ISSUE THREAD

**Issue by KenSpur** [PacoVK/tapir#455]
tapir allows me to upload module versions with prefixes (e.g., v0.1.0), but Terraform can only download unprefixed, versions like 0.1.0. It seems there’s no validation during upload to ensure version formats are compatible with the downloads.

I’m using tapir 0.9.0 with CosmosDB and Azure Storage.

**Comment by PacoVK** [comment]
Indeed there is no validation, I will take a look to add that to the upload to ensure only compatible modules can be added to the registry 👍
